const WHATSAPP='2349014970078';
const properties=[
{id:1,title:'Contemporary 4 Bedroom Duplex',type:'Duplex',location:'Rukpokwu',area:'SARS Road axis',price:150000000,beds:4,baths:5,land:'Approx. 450 sqm',tag:'Featured',image:'house1.jpg',description:'A spacious contemporary family duplex concept with ensuite bedrooms, a fitted kitchen, family lounge, parking area and secure compound. Sample listing — confirm availability and specifications with Danny’s Estate.'},
{id:2,title:'Modern 3 Bedroom Apartment',type:'Apartment',location:'GRA',area:'Port Harcourt',price:85000000,beds:3,baths:3,land:'Apartment',tag:'New listing',image:'house2.jpg',description:'A modern apartment concept designed for comfortable city living, with generous living spaces, contemporary finishes, parking and a secure residential setting. Sample listing — confirm availability and specifications with Danny’s Estate.'},
{id:3,title:'Executive 5 Bedroom Residence',type:'Duplex',location:'Peter Odili Road',area:'Port Harcourt',price:280000000,beds:5,baths:6,land:'Approx. 500 sqm',tag:'Premium',image:'house3.jpg',description:'An upscale five-bedroom residence concept with spacious entertaining areas, landscaped grounds, ample parking and a premium finish. Sample listing — confirm availability and specifications with Danny’s Estate.'},
{id:4,title:'Tasteful 3 Bedroom Bungalow',type:'Bungalow',location:'Rukpokwu',area:'Apu Road axis',price:65000000,beds:3,baths:3,land:'Approx. 320 sqm',tag:'Value pick',image:'house4.jpg',description:'A practical single-storey home concept suited to families seeking easy movement, a fenced compound, parking and a quiet residential setting. Sample listing — confirm availability and specifications with Danny’s Estate.'},
{id:5,title:'Residential Land Opportunity',type:'Land',location:'Rukpokwu',area:'Obirikwere axis',price:20000000,beds:0,baths:0,land:'Plot — confirm size',tag:'Investment',image:'house4.jpg',description:'A sample residential land opportunity for buyers planning a future build. Title, dimensions, survey and exact location should be independently verified before purchase.'},
{id:6,title:'4 Bedroom Semi-Detached Duplex',type:'Duplex',location:'SARS Road',area:'Port Harcourt',price:210000000,beds:4,baths:5,land:'Approx. 450 sqm',tag:'New build',image:'house1.jpg',description:'A modern semi-detached duplex concept with family lounge, fitted kitchen, bedrooms ensuite, parking and a secure estate setting. Sample listing — confirm availability and specifications with Danny’s Estate.'}
];
const money=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n);
const grid=document.getElementById('propertyGrid'), empty=document.getElementById('emptyState');
function render(list=properties){grid.innerHTML=list.map(p=>`<article class="property-card"><div class="property-image"><img src="${p.image}" alt="${p.title}" loading="lazy"><span>${p.tag}</span></div><div class="property-body"><div class="property-top"><span>${p.beds?p.beds+' Beds · '+p.baths+' Baths':'Residential land'}</span><strong>${money(p.price)}</strong></div><h3>${p.title}</h3><p>${p.location} · ${p.area}</p><button class="details-btn" data-id="${p.id}">View details →</button></div></article>`).join('');empty.style.display=list.length?'none':'block';}
function search(){const l=document.getElementById('locationFilter').value,t=document.getElementById('typeFilter').value,b=Number(document.getElementById('budgetFilter').value||0);render(properties.filter(p=>(!l||p.location===l)&&(!t||p.type===t)&&(!b||p.price<=b)));document.getElementById('properties').scrollIntoView({behavior:'smooth'});}
['locationFilter','typeFilter','budgetFilter'].forEach(id=>document.getElementById(id).addEventListener('change',search));document.getElementById('searchBtn').addEventListener('click',search);render();
const menuToggle=document.querySelector('.menu-toggle'),navLinks=document.querySelector('.nav-links');menuToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const modal=document.getElementById('propertyModal');function openModal(p){document.getElementById('modalImage').src=p.image;document.getElementById('modalImage').alt=p.title;document.getElementById('modalTitle').textContent=p.title;document.getElementById('modalTag').textContent=p.tag;document.getElementById('modalMeta').textContent=`${money(p.price)} · ${p.location} · ${p.land}${p.beds?' · '+p.beds+' beds · '+p.baths+' baths':''}`;document.getElementById('modalDescription').textContent=p.description;document.getElementById('modalWhatsapp').href=`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hello Danny's Estate, I'm interested in ${p.title} (${money(p.price)}). Please send me more details.`)}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
grid.addEventListener('click',e=>{const btn=e.target.closest('.details-btn');if(btn)openModal(properties.find(p=>p.id===Number(btn.dataset.id)))});function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim(),phone=document.getElementById('phone').value.trim(),msg=document.getElementById('message').value.trim();const text=`Hello Danny's Estate,%0A%0AName: ${encodeURIComponent(n)}%0AEmail: ${encodeURIComponent(email)}%0APhone: ${encodeURIComponent(phone)}%0ARequirement: ${encodeURIComponent(msg)}`;window.open(`https://wa.me/${WHATSAPP}?text=${text}`,'_blank');document.getElementById('formStatus').textContent='WhatsApp opened with your enquiry. Please send the message to complete the enquiry.';e.target.reset();});
